// SPDX-License-Identifier: GPL-3.0-or-later

//! Embeds the SQL migration scripts from `vault-spec/migrations/` so the crate
//! stays the single place that knows the schema. Generates an ordered
//! `MIGRATIONS` array and the highest known `SCHEMA_VERSION` (spec §7.1).

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let migrations_dir = manifest_dir.join("../../vault-spec/migrations");

    println!("cargo:rerun-if-changed={}", migrations_dir.display());
    let migrations = collect(&migrations_dir);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    let generated = render(&migrations);
    fs::write(out_dir.join("migrations_generated.rs"), generated)
        .expect("writing the generated migrations file");
}

/// Collects `<number>_<name>.sql` files, ascending by number.
fn collect(dir: &Path) -> Vec<(i64, PathBuf)> {
    let entries =
        fs::read_dir(dir).unwrap_or_else(|error| panic!("reading {}: {error}", dir.display()));

    let mut migrations = Vec::new();
    for entry in entries {
        let path = entry.expect("a readable directory entry").path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("sql") {
            continue;
        }

        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .expect("a UTF-8 migration file name");
        let number = name
            .split('_')
            .next()
            .and_then(|prefix| prefix.parse::<i64>().ok())
            .unwrap_or_else(|| {
                panic!("migration {name} must be named NNNN_name.sql");
            });

        println!("cargo:rerun-if-changed={}", path.display());
        migrations.push((number, path));
    }

    migrations.sort_by_key(|(number, _)| *number);
    assert!(
        !migrations.is_empty(),
        "no migrations found in {}",
        dir.display()
    );
    migrations
}

/// Renders the generated Rust module.
fn render(migrations: &[(i64, PathBuf)]) -> String {
    let schema_version = migrations.last().map(|(number, _)| *number).unwrap_or(0);

    let mut out = String::from("// @generated by build.rs; do not edit.\n");
    out.push_str("pub const MIGRATIONS: &[(i64, &str)] = &[\n");
    for (number, path) in migrations {
        let path = path.display();
        writeln!(
            out,
            "    ({number}, include_str!(\"{path}\")),",
            number = number,
            path = path
        )
        .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");
    writeln!(out, "pub const SCHEMA_VERSION: i64 = {schema_version};")
        .expect("writing to a String cannot fail");
    out
}
