# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "quaderno"
description = "Private, encrypted personal journal for GNOME"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[build-dependencies]
glib-build-tools = "0.22"

[dependencies]
gtk = { workspace = true }
adw = { workspace = true }
quaderno-vault = { workspace = true }
oo7 = { workspace = true }
gettext-rs = { workspace = true }
tokio = { workspace = true }
futures-channel = { workspace = true }
zeroize = { workspace = true }

[[bin]]
name = "quaderno"
path = "src/main.rs"
